global:
  scrape_interval: 250ms
  evaluation_interval: 250ms

scrape_configs:
  - job_name: "harness"
    static_configs:
      - targets: ["harness:9464"]
  - job_name: "clients_api"
    static_configs:
      - targets: ["api:8080"]
